[package]
name = "webserver"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-rt = "2.11.0"
actix-web = "4"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
serde = {version = "1.0.227", features = ["derive"]}
sha1 = "0.10.6"
tokio = "1.48.0"
